postgres:
  image: postgres:9.4.5
  environment:
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
  ports:
    - '5432:5432'
  volumes:
    - sample_postgres:/var/lib/postgresql/data

sample:
  image: rails-sample-guestbook:latest
  links:
    - postgres
  ports:
    - '3000:3000'
  environment:
    DATABASE_URL: postgresql://user:password@postgres
